name: Update vorstossdaten data

on:
  workflow_dispatch:
  schedule:
    - cron: '41 07 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    container: rocker/tidyverse:4.1.2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with: 
        token: ${{ secrets.PAT }}


    - name: Execute script 
      env: 
        PAT: ${{ secrets.PAT }}


      run: |
        Rscript user_scraper.R

  
      # Commit and push all changed files.
    - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
      # Only run on main branch push (e.g. after pull request merge).
      run: |
        git config --global --add safe.directory /__w/vorstossdaten_scrape/vorstossdaten_scrape
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git pull
        git add .
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
